/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HierarchyRouteImport } from './routes/hierarchy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesCapabilityIdRouteImport } from './routes/capabilities.$capabilityId'

const HierarchyRoute = HierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesCapabilityIdRoute =
  CapabilitiesCapabilityIdRouteImport.update({
    id: '/capabilities/$capabilityId',
    path: '/capabilities/$capabilityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hierarchy': typeof HierarchyRoute
  '/capabilities/$capabilityId': typeof CapabilitiesCapabilityIdRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hierarchy': typeof HierarchyRoute
  '/capabilities/$capabilityId': typeof CapabilitiesCapabilityIdRoute
  '/capabilities': typeof CapabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hierarchy': typeof HierarchyRoute
  '/capabilities/$capabilityId': typeof CapabilitiesCapabilityIdRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hierarchy'
    | '/capabilities/$capabilityId'
    | '/capabilities/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hierarchy' | '/capabilities/$capabilityId' | '/capabilities'
  id:
    | '__root__'
    | '/'
    | '/hierarchy'
    | '/capabilities/$capabilityId'
    | '/capabilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HierarchyRoute: typeof HierarchyRoute
  CapabilitiesCapabilityIdRoute: typeof CapabilitiesCapabilityIdRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hierarchy': {
      id: '/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof HierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$capabilityId': {
      id: '/capabilities/$capabilityId'
      path: '/capabilities/$capabilityId'
      fullPath: '/capabilities/$capabilityId'
      preLoaderRoute: typeof CapabilitiesCapabilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HierarchyRoute: HierarchyRoute,
  CapabilitiesCapabilityIdRoute: CapabilitiesCapabilityIdRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
